package model

// Announcement object
type Announcement struct {
	AllowRating             bool        `json:"allow_rating"`
	AssignmentID            interface{} `json:"assignment_id"`
	Attachments             []File      `json:"attachments"`
	Author                  interface{} `json:"author"`
	CanGroup                bool        `json:"can_group"`
	CanLock                 bool        `json:"can_lock"`
	CanUnpublish            bool        `json:"can_unpublish"`
	CommentsDisabled        bool        `json:"comments_disabled"`
	ContextCode             string      `json:"context_code"`
	CreatedAt               string      `json:"created_at"`
	DelayedPostAt           interface{} `json:"delayed_post_at"`
	DiscussionSubentryCount int         `json:"discussion_subentry_count"`
	DiscussionType          string      `json:"discussion_type"`
	GroupCategoryID         interface{} `json:"group_category_id"`
	GroupTopicChildren      interface{} `json:"group_topic_children"`
	HTMLURL                 string      `json:"html_url"`
	ID                      int         `json:"id"`
	IsSectionSpecific       bool        `json:"is_section_specific"`
	LastReplyAt             string      `json:"last_reply_at"`
	LockAt                  interface{} `json:"lock_at"`
	LockExplanation         string      `json:"lock_explanation"`
	LockInfo                interface{} `json:"lock_info"`
	Locked                  bool        `json:"locked"`
	LockedForUser           bool        `json:"locked_for_user"`
	Message                 string      `json:"message"`
	OnlyGradersCanRate      bool        `json:"only_graders_can_rate"`
	Permissions             interface{} `json:"permissions"`
	Pinned                  bool        `json:"pinned"`
	PodcastHasStudentPosts  bool        `json:"podcast_has_student_posts"`
	PodcastURL              interface{} `json:"podcast_url"`
	Position                int         `json:"position"`
	PostedAt                string      `json:"posted_at"`
	Published               bool        `json:"published"`
	ReadState               string      `json:"read_state"`
	RequireInitialPost      interface{} `json:"require_initial_post"`
	RootTopicID             interface{} `json:"root_topic_id"`
	SortByRating            bool        `json:"sort_by_rating"`
	Subscribed              bool        `json:"subscribed"`
	SubscriptionHold        string      `json:"subscription_hold"`
	Title                   string      `json:"title"`
	TodoDate                interface{} `json:"todo_date"`
	TopicChildren           interface{} `json:"topic_children"`
	URL                     string      `json:"url"`
	UnreadCount             int         `json:"unread_count"`
	UserCanSeePosts         bool        `json:"user_can_see_posts"`
	UserName                string      `json:"user_name"`
}
