package model

// Course object
type Course struct {
	AccessRestrictedByDate            bool        `json:"access_restricted_by_date"`
	AccountID                         int         `json:"account_id"`
	AllowStudentAssignmentEdits       bool        `json:"allow_student_assignment_edits"`
	AllowStudentForumAttachments      bool        `json:"allow_student_forum_attachments"`
	AllowWikiComments                 bool        `json:"allow_wiki_comments"`
	ApplyAssignmentGroupWeights       bool        `json:"apply_assignment_group_weights"`
	Blueprint                         bool        `json:"blueprint"`
	BlueprintRestrictions             interface{} `json:"blueprint_restrictions"`
	BlueprintRestrictionsByObjectType interface{} `json:"blueprint_restrictions_by_object_type"`
	Calendar                          interface{} `json:"calendar"`
	CourseCode                        string      `json:"course_code"`
	CourseFormat                      string      `json:"course_format"`
	CourseProgress                    interface{} `json:"course_progress"`
	CreatedAt                         string      `json:"created_at"`
	DefaultView                       string      `json:"default_view"`
	EndAt                             string      `json:"end_at"`
	EnrollmentTermID                  int         `json:"enrollment_term_id"`
	Enrollments                       interface{} `json:"enrollments"`
	GradePassbackSetting              string      `json:"grade_passback_setting"`
	GradingStandardID                 int         `json:"grading_standard_id"`
	HideFinalGrades                   bool        `json:"hide_final_grades"`
	ID                                int         `json:"id"`
	IntegrationID                     interface{} `json:"integration_id"`
	IsPublic                          bool        `json:"is_public"`
	IsPublicToAuthUsers               bool        `json:"is_public_to_auth_users"`
	License                           string      `json:"license"`
	Locale                            string      `json:"locale"`
	Name                              string      `json:"name"`
	NeedsGradingCount                 int         `json:"needs_grading_count"`
	OpenEnrollment                    bool        `json:"open_enrollment"`
	Permissions                       interface{} `json:"permissions"`
	PublicDescription                 string      `json:"public_description"`
	PublicSyllabus                    bool        `json:"public_syllabus"`
	PublicSyllabusToAuth              bool        `json:"public_syllabus_to_auth"`
	RestrictEnrollmentsToCourseDates  bool        `json:"restrict_enrollments_to_course_dates"`
	RootAccountID                     int         `json:"root_account_id"`
	SelfEnrollment                    bool        `json:"self_enrollment"`
	SisCourseID                       interface{} `json:"sis_course_id"`
	SisImportID                       int         `json:"sis_import_id"`
	StartAt                           string      `json:"start_at"`
	StorageQuotaMb                    int         `json:"storage_quota_mb"`
	StorageQuotaUsedMb                int         `json:"storage_quota_used_mb"`
	SyllabusBody                      string      `json:"syllabus_body"`
	Term                              interface{} `json:"term"`
	TimeZone                          string      `json:"time_zone"`
	TotalStudents                     int         `json:"total_students"`
	UUID                              string      `json:"uuid"`
	WorkflowState                     string      `json:"workflow_state"`
}
